// categories
export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';
export const LOADING_CATEGORIES_LIST = 'LOADING_CATEGORIES_LIST';
// table5
export const GET_TABLE5_CATEGORIES = 'GET_TABLE5_CATEGORIES';
export const LOADING_TABLE5_CATEGORIES = 'LOADING_TABLE5_CATEGORIES';
export const GET_TABLE5_INFO_BY_ID = 'GET_TABLE5_INFO_BY_ID';
export const LOADING_TABLE5_INFO_BY_ID = 'LOADING_TABLE5_INFO_BY_ID';
// resips
export const GET_RECIPS_LIST = 'GET_RECIPS_LIST';
export const LOADING_RECIPS_LIST = 'LOADING_RECIPS_LIST';
export const GET_CATEGORIES_RECIPS_LIST = 'GET_CATEGORIES_RECIPS_LIST';
export const LOADING_CATEGORIES_RECIPS_LIST = 'LOADING_CATEGORIES_RECIPS_LIST';
export const GET_RECIP_BY_ID = 'GET_RECIP_BY_ID';
export const LOADING_RECIP_BY_ID = 'LOADING_RECIP_BY_ID';
// search by recipes
export const GET_SEARCH_RECIPES_LIST = 'GET_SEARCH_RECIPES_LIST';
export const LOADING_SEARCH_RECIPES_LIST = 'LOADING_SEARCH_RECIPES_LIST';
export const SHOW_SEARCH_LAYOUT = 'SHOW_SEARCH_LAYOUT';
// menu week
export const GET_MENU_WEEK_LIST = 'GET_MENU_WEEK_LIST';
export const LOADING_MENU_WEEK_LIST = 'LOADING_MENU_WEEK_LIST';
// liverArticles
export const GET_LIVER_ARTICLES_LIST = 'GET_LIVER_ARTICLES_LIST';
export const LOADING_LIVER_ARTICLES_LIST = 'LOADING_LIVER_ARTICLES_LIST';
// treats
export const GET_TREATS_LIST = 'GET_TREATS_LIST';
export const LOADING_TREATS_LIST = 'LOADING_TREATS_LIST';
// article
export const GET_CUR_ARTICLE = 'GET_CUR_ARTICLE';
export const LOADING_CUR_ARTICLE = 'LOADING_CUR_ARTICLE';
// diseases
export const GET_DISEASES_LIST = 'GET_DISEASES_LIST';
export const LOADING_DISEASES_LIST = 'LOADING_DISEASES_LIST';
// legal info
export const GET_LEGAL_INFO_LIST = 'GET_LEGAL_INFO_LIST';
export const LOADING_LEGAL_INFO_LIST = 'LOADING_LEGAL_INFO_LIST';
// allData
export const IS_LOADED_DATA = 'IS_LOADED_DATA';
export const CHECK_LOADING_ALL_DATA = 'CHECK_LOADING_ALL_DATA';
export const LOADING_ALL_DATA = 'LOADING_ALL_DATA';
export const GET_ALL_DATA_RECIPES_WITH_DETAILS =
  'GET_ALL_DATA_RECIPES_WITH_DETAILS';
export const GET_ALL_DATA_CAN_EAT_LIST = 'GET_ALL_DATA_CAN_EAT_LIST';
export const GET_ALL_DATA_ARTICLES_LIST = 'GET_ALL_DATA_ARTICLES_LIST';
export const GET_ALL_DATA_SEARCH_CAN_EAT_LIST =
  'GET_ALL_DATA_SEARCH_CAN_EAT_LIST';
export const SET_MOBILE_DEVICE = 'SET_MOBILE_DEVICE';
